import type {
  B8ReadinessDossier,
  EvidenceRequirement,
  MeasurementRule,
  ReopenSignal,
  StopRule,
} from "../../core/b8-readiness.js";

const requirements: EvidenceRequirement[] = [
  {
    requirementId: "B8-LRN-01",
    gateId: "LEARNING_FEASIBILITY",
    title: "Norsk språkfaglig review av mønsterklasse og stimuli",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "BLOCKED",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "NORSK-SPRAAKFAGLIG-REVIEWER",
    evidenceRefs: ["docs/WP13_2_PATTERN_DECISION.md"],
    limitation: "Sol–mus er et engineering-proof, ikke en godkjent intervensjon eller stimulusbank.",
  },
  {
    requirementId: "B8-LRN-02",
    gateId: "LEARNING_FEASIBILITY",
    title: "Forhåndsdefinert feasibility-måleplan uten effektpåstand",
    level: "REQUIRED",
    dueBefore: "B8_DECISION",
    status: "DRAFT",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "EVALUERINGSANSVARLIG",
    evidenceRefs: ["B8-MEASURE-01", "B8-MEASURE-02"],
    limitation: "Proofet viser mekanisk gjennomførbarhet, ikke læringseffekt.",
  },
  {
    requirementId: "B8-LRN-03",
    gateId: "LEARNING_FEASIBILITY",
    title: "Syntetisk target- og near-transfer-flyt består",
    level: "REQUIRED",
    dueBefore: "B8_DECISION",
    status: "SYNTHETIC_PASS",
    acceptedStatuses: ["SYNTHETIC_PASS", "HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "TEKNISK-REVISOR",
    evidenceRefs: ["tests/scenarios/vertical-proof.test.ts", "artifacts/wp13-2-complete.png"],
    limitation: "Ingen konklusjon om generalisering til barn kan trekkes.",
  },
  {
    requirementId: "B8-HP-01",
    gateId: "HUMAN_FIRST",
    title: "HF-S01–HF-S12 og Human-First static gate består",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "SYNTHETIC_PASS",
    acceptedStatuses: ["SYNTHETIC_PASS", "HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "HUMAN-FIRST-REVISOR",
    evidenceRefs: ["tests/scenarios/human-first.test.ts", "scripts/static-check.mjs"],
    limitation: "Maskinelle bevis kan ikke erstatte barns og voksnes opplevelse.",
  },
  {
    requirementId: "B8-HP-02",
    gateId: "HUMAN_FIRST",
    title: "Co-design-protokoll med robotaktighet, stillhet, valg og voksenmyndighet",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "DRAFT",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "CO-DESIGN-ANSVARLIG",
    evidenceRefs: ["docs/WP13_4_B8_EVIDENCE_AND_PILOT_READINESS.md"],
    limitation: "Ingen deltakere kan rekrutteres før B8.",
  },
  {
    requirementId: "B8-HP-03",
    gateId: "HUMAN_FIRST",
    title: "Uavhengig voksen- og barnevennlig språk-/verdighetsreview",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "BLOCKED",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "EKSTERN-HUMAN-FIRST-REVIEWER",
    evidenceRefs: [],
    limitation: "Produktteamets egen vurdering er utilstrekkelig før barn involveres.",
  },
  {
    requirementId: "B8-SAFE-01",
    gateId: "CHILD_SAFETY",
    title: "Kritiske stoppregler og restartmyndighet er eksplisitt",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "HUMAN_REVIEW_PASS",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "PRODUKTEIER",
    evidenceRefs: ["B8-STOP-01", "B8-STOP-02", "B8-STOP-03", "B8-STOP-04"],
    limitation: "Reglene er ikke prøvd i en faktisk pilotsituasjon.",
  },
  {
    requirementId: "B8-SAFE-02",
    gateId: "CHILD_SAFETY",
    title: "Barnet kan pause og stoppe uten straff eller gjenoppliving",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "SYNTHETIC_PASS",
    acceptedStatuses: ["SYNTHETIC_PASS", "HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "TEKNISK-REVISOR",
    evidenceRefs: ["tests/properties/state-machine.test.ts", "tests/scenarios/vertical-proof.test.ts"],
    limitation: "Må senere bekreftes med representativ bruker og hjelpemiddel.",
  },
  {
    requirementId: "B8-SAFE-03",
    gateId: "CHILD_SAFETY",
    title: "Beredskapslinje ved ubehag, stigma eller personvernhendelse",
    level: "CRITICAL",
    dueBefore: "RECRUITMENT",
    status: "DRAFT",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "PILOTANSVARLIG",
    evidenceRefs: ["docs/WP13_4_B8_EVIDENCE_AND_PILOT_READINESS.md"],
    limitation: "Navngitte personer og kontaktkanaler finnes ikke før pilotpartner er valgt.",
  },
  {
    requirementId: "B8-A11Y-01",
    gateId: "ACCESSIBILITY",
    title: "Automatisert tastatur-, fokus-, reflow- og tilgjengelighetstreproof",
    level: "REQUIRED",
    dueBefore: "B8_DECISION",
    status: "SYNTHETIC_PASS",
    acceptedStatuses: ["SYNTHETIC_PASS", "HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "UU-ANSVARLIG",
    evidenceRefs: ["scripts/browser-accessibility-test.mjs", "scripts/browser-knowledge-test.mjs"],
    limitation: "Automatisert kontroll dekker ikke all faktisk hjelpemiddelbruk.",
  },
  {
    requirementId: "B8-A11Y-02",
    gateId: "ACCESSIBILITY",
    title: "Manuell skjermleser- og tastaturreview av kritisk flyt",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "BLOCKED",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "EKSTERN-UU-REVIEWER",
    evidenceRefs: [],
    limitation: "Må gjennomføres uten å rekruttere barn før B8.",
  },
  {
    requirementId: "B8-A11Y-03",
    gateId: "ACCESSIBILITY",
    title: "Plan for representativ tilgjengelighetstest etter B8",
    level: "REQUIRED",
    dueBefore: "B8_DECISION",
    status: "DRAFT",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "UU-ANSVARLIG",
    evidenceRefs: ["docs/WP13_4_B8_EVIDENCE_AND_PILOT_READINESS.md"],
    limitation: "Gjennomføring er blokkert til B8.",
  },
  {
    requirementId: "B8-ADULT-01",
    gateId: "ADULT_WORKLOAD",
    title: "Voksenkortet er ett, kort, avvisbart og har WAIT",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "SYNTHETIC_PASS",
    acceptedStatuses: ["SYNTHETIC_PASS", "HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "GUIDED-DYAD-ANSVARLIG",
    evidenceRefs: ["tests/scenarios/vertical-proof.test.ts", "src/core/content-contracts.ts"],
    limitation: "Arbeidsbelastningen er ennå ikke målt med faktiske voksne.",
  },
  {
    requirementId: "B8-ADULT-02",
    gateId: "ADULT_WORKLOAD",
    title: "Adult-only dry-run-protokoll og belastningsterskel",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "DRAFT",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "PILOTANSVARLIG",
    evidenceRefs: ["B8-MEASURE-10"],
    limitation: "Dry-run kan ikke utføres før riktig autorisasjon.",
  },
  {
    requirementId: "B8-CAK-01",
    gateId: "CONTENT_AUDIO_KNOWLEDGE",
    title: "BM/NN, knowledge, context cards og audio ligger i én releasegraf",
    level: "REQUIRED",
    dueBefore: "B8_DECISION",
    status: "SYNTHETIC_PASS",
    acceptedStatuses: ["SYNTHETIC_PASS", "HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "INNHOLDSARKITEKT",
    evidenceRefs: ["tests/content/knowledge-audio-prototype.test.ts"],
    limitation: "Innholdet er prototypeinnhold, ikke pilotgodkjent.",
  },
  {
    requirementId: "B8-CAK-02",
    gateId: "CONTENT_AUDIO_KNOWLEDGE",
    title: "Språk-, pedagogikk-, alder-/verdighets- og kilde-review",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "BLOCKED",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "REDAKSJONSANSVARLIG",
    evidenceRefs: [],
    limitation: "Internt prototype-review er ikke tilstrekkelig for pilot.",
  },
  {
    requirementId: "B8-CAK-03",
    gateId: "CONTENT_AUDIO_KNOWLEDGE",
    title: "Menneskelig pilotlyd med rettigheter, uttale- og withdrawal-review",
    level: "CRITICAL",
    dueBefore: "FIRST_SESSION",
    status: "BLOCKED",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "AUDIOANSVARLIG",
    evidenceRefs: ["docs/WP13_3_AUDIO_KNOWLEDGE_PROTOTYPE.md"],
    limitation: "Dagens fire WAV-filer er syntetiske kladder for intern vurdering.",
  },
  {
    requirementId: "B8-PRIV-01",
    gateId: "PRIVACY_LEGAL_ETHICS",
    title: "Skoleeier/behandlingsansvarlig og leverandørroller er identifisert",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "BLOCKED",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "SKOLEEIER-PERSONVERN",
    evidenceRefs: ["SRC-UDIR-SCHOOL-OWNER"],
    limitation: "Ingen pilotpartner eller skoleeier er valgt.",
  },
  {
    requirementId: "B8-PRIV-02",
    gateId: "PRIVACY_LEGAL_ETHICS",
    title: "Datainventar, formål, behandlingsgrunnlag, sletting og avtaler",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "DRAFT",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "PERSONVERNANSVARLIG",
    evidenceRefs: ["SRC-UDIR-PERSONAL-DATA", "SRC-DT-SCHOOL-AUDIT"],
    limitation: "Appens nullprofil er definert, men evalueringsdata og juridisk grunnlag er ikke godkjent.",
  },
  {
    requirementId: "B8-PRIV-03",
    gateId: "PRIVACY_LEGAL_ETHICS",
    title: "DPIA-screening og eventuell full DPIA er godkjent",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "BLOCKED",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED", "NOT_APPLICABLE"],
    ownerRole: "PERSONVERNANSVARLIG",
    evidenceRefs: ["SRC-DT-DPIA"],
    limitation: "Barn, skolekontekst og ny løsning gjør at DPIA-spørsmålet må avgjøres eksplisitt.",
  },
  {
    requirementId: "B8-ETH-01",
    gateId: "PRIVACY_LEGAL_ETHICS",
    title: "Pilotens status som produktutprøving, forskning eller kvalitetsarbeid er klassifisert",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "BLOCKED",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "ETIKK-/EVALUERINGSANSVARLIG",
    evidenceRefs: ["SRC-NESH-CONSENT"],
    limitation: "Riktig godkjenningsløp avhenger av formål, metode og planlagt publisering.",
  },
  {
    requirementId: "B8-ETH-02",
    gateId: "PRIVACY_LEGAL_ETHICS",
    title: "Alderstilpasset informasjon, aktivt foresattesamtykke og barns assent",
    level: "CRITICAL",
    dueBefore: "RECRUITMENT",
    status: "DRAFT",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "PILOTANSVARLIG",
    evidenceRefs: ["SRC-NESH-CONSENT"],
    limitation: "Aktivt, informert og uttrykkelig samtykke brukes som konservativ baseline.",
  },
  {
    requirementId: "B8-AI-01",
    gateId: "PRIVACY_LEGAL_ETHICS",
    title: "Gjeldende AI-regelverk og markedsføringspåstander er juridisk gjennomgått",
    level: "REQUIRED",
    dueBefore: "B8_DECISION",
    status: "DRAFT",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED", "NOT_APPLICABLE"],
    ownerRole: "JURIDISK-ANSVARLIG",
    evidenceRefs: ["SRC-UDIR-AI-PRIVACY", "SRC-EU-AI-ACT"],
    limitation: "Produktet har ingen runtime-AI, men authoringbruk og produktpåstander må fortsatt klassifiseres.",
  },
  {
    requirementId: "B8-SEC-01",
    gateId: "SECURITY_OPERATIONS",
    title: "Trusselmodell og sikkerhetskrav for pilotmiljø",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "DRAFT",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "SIKKERHETSANSVARLIG",
    evidenceRefs: ["docs/WP13_4_B8_EVIDENCE_AND_PILOT_READINESS.md"],
    limitation: "Provider og miljø er ikke valgt.",
  },
  {
    requirementId: "B8-SEC-02",
    gateId: "SECURITY_OPERATIONS",
    title: "Separat provider-, credential-, preview-, data- og rollbackgrense",
    level: "CRITICAL",
    dueBefore: "RECRUITMENT",
    status: "BLOCKED",
    acceptedStatuses: ["EXTERNAL_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "TEKNISK-ANSVARLIG",
    evidenceRefs: [],
    limitation: "Provider er med vilje ikke valgt eller opprettet.",
  },
  {
    requirementId: "B8-OPS-01",
    gateId: "SECURITY_OPERATIONS",
    title: "Incident-, support-, withdrawal- og rollbackrunbook med navngitte roller",
    level: "CRITICAL",
    dueBefore: "RECRUITMENT",
    status: "DRAFT",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "PILOTANSVARLIG",
    evidenceRefs: ["docs/WP13_4_B8_EVIDENCE_AND_PILOT_READINESS.md"],
    limitation: "Navngitte roller kan ikke ferdigstilles før pilotpartner finnes.",
  },
  {
    requirementId: "B8-PROT-01",
    gateId: "PILOT_PROTOCOL",
    title: "Staged pilotprotokoll med liten, reversibel dyadepilot",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "HUMAN_REVIEW_PASS",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "PRODUKTEIER",
    evidenceRefs: ["PILOT-ENVELOPE-13-4"],
    limitation: "Protokollen er et forslag og gir ingen autorisasjon.",
  },
  {
    requirementId: "B8-PROT-02",
    gateId: "PILOT_PROTOCOL",
    title: "Måle-, stopp- og beslutningsregler er frosset før rekruttering",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "DRAFT",
    acceptedStatuses: ["HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "EVALUERINGSANSVARLIG",
    evidenceRefs: ["B8-STOP-01", "B8-MEASURE-01", "B8-MEASURE-10"],
    limitation: "Terskelforslagene krever ekstern og eiermessig godkjenning.",
  },
  {
    requirementId: "B8-PROT-03",
    gateId: "PILOT_PROTOCOL",
    title: "B8-beslutningsnotat skiller beslutningsklar fra pilotgodkjent",
    level: "CRITICAL",
    dueBefore: "B8_DECISION",
    status: "SYNTHETIC_PASS",
    acceptedStatuses: ["SYNTHETIC_PASS", "HUMAN_REVIEW_PASS", "OWNER_ACCEPTED"],
    ownerRole: "PRODUKTEIER",
    evidenceRefs: ["src/core/b8-readiness.ts"],
    limitation: "Evidensmotoren kan ikke autorisere rekruttering, ekte data eller pilot.",
  },
];

const stopRules: StopRule[] = [
  {
    stopRuleId: "B8-STOP-01",
    severity: "CRITICAL",
    trigger: "Barnet ber om stopp, viser tydelig ubehag, eller den voksne vurderer at aktiviteten bør stoppe.",
    immediateAction: "STOP_SESSION",
    restartAuthority: "NO_RESTART_WITHOUT_NEW_B8",
    evidenceRequiredForRestart: ["hendelsesreview", "oppdatert sikkerhetsregel", "ny eksplisitt autorisasjon"],
  },
  {
    stopRuleId: "B8-STOP-02",
    severity: "CRITICAL",
    trigger: "Stop/pause virker ikke, slettet økt gjenopplives, eller skjult person-/elevdata oppstår.",
    immediateAction: "PAUSE_PILOT",
    restartAuthority: "NO_RESTART_WITHOUT_NEW_B8",
    evidenceRequiredForRestart: ["rotårsaksanalyse", "regresjonstest", "personvern-/sikkerhetsgodkjenning"],
  },
  {
    stopRuleId: "B8-STOP-03",
    severity: "CRITICAL",
    trigger: "Barnet tror systemet kjenner, føler, lytter til eller diagnostiserer det på en måte som produktet ikke gjør.",
    immediateAction: "PAUSE_PILOT",
    restartAuthority: "PRODUCT_OWNER",
    evidenceRequiredForRestart: ["språk-/transparensendring", "Human-First-review", "ny dry-run"],
  },
  {
    stopRuleId: "B8-STOP-04",
    severity: "MAJOR",
    trigger: "Samme robotaktige, stigmatiserende, overstyrende eller utilgjengelige problem opptrer i to økter.",
    immediateAction: "PAUSE_PILOT",
    restartAuthority: "PILOT_LEAD",
    evidenceRequiredForRestart: ["remediation", "målrettet retest", "dokumentert aksept"],
  },
  {
    stopRuleId: "B8-STOP-05",
    severity: "MINOR",
    trigger: "En enkelt ikke-kritisk formulering, timing eller kontroll skaper friksjon uten skade eller tap av kontroll.",
    immediateAction: "LOG_AND_REVIEW",
    restartAuthority: "PILOT_LEAD",
    evidenceRequiredForRestart: ["prioritering i avvikslogg"],
  },
];

const reopenSignals: ReopenSignal[] = [
  {
    signalId: "B8-REOPEN-01",
    description: "Pilot krever stabil elevprofil eller kryssøktidentitet.",
    triggered: false,
    evidenceRefs: [],
  },
  {
    signalId: "B8-REOPEN-02",
    description: "Første pilot krever runtime-AI eller fri coachingtekst.",
    triggered: false,
    evidenceRefs: [],
  },
  {
    signalId: "B8-REOPEN-03",
    description: "Separat provider-, data- eller deploygrense kan ikke etableres.",
    triggered: false,
    evidenceRefs: [],
  },
  {
    signalId: "B8-REOPEN-04",
    description: "No-resurrection eller voksenmyndighet kan ikke håndheves.",
    triggered: false,
    evidenceRefs: [],
  },
];

const measurementRules: MeasurementRule[] = [
  {
    measureId: "B8-MEASURE-01",
    domain: "LEARNING",
    question: "Forstår barnet oppgaven og gjennomfører målbygging med tillatt støtte?",
    collectionMethod: "STRUCTURED_OBSERVATION",
    applicationLoggingRequired: false,
    thresholdProposal: "Minst N-1 av 6–8 dyader gjennomfører målbygging; resultatet er feasibility, ikke effekt.",
    blocksContinuationWhen: "To eller flere dyader kan ikke forstå kjernehandlingen etter tillatt forklaring.",
  },
  {
    measureId: "B8-MEASURE-02",
    domain: "LEARNING",
    question: "Forsøker barnet near transfer etter støtte uten at evidensstatus omskrives?",
    collectionMethod: "STRUCTURED_OBSERVATION",
    applicationLoggingRequired: false,
    thresholdProposal: "Minst N-1 dyader gjennomfører ett transferforsøk; korrekthet rapporteres deskriptivt.",
    blocksContinuationWhen: "Transferoppgaven er systematisk uklar eller avslører et annet konstrukt enn planlagt.",
  },
  {
    measureId: "B8-MEASURE-03",
    domain: "HUMAN_FIRST",
    question: "Vet barnet at den faktiske voksne gir pedagogisk støtte?",
    collectionMethod: "POST_SESSION_QUESTION",
    applicationLoggingRequired: false,
    thresholdProposal: "Alle barn skal kunne forklare at appen er et verktøy og den voksne hjelper; ett kritisk misforhold utløser pause.",
    blocksContinuationWhen: "Barnet tillegger systemet falsk relasjon, lytting, følelser eller diagnose.",
  },
  {
    measureId: "B8-MEASURE-04",
    domain: "HUMAN_FIRST",
    question: "Kan barnet bruke arbeidsro, hjelp, pause og stopp som reelle valg?",
    collectionMethod: "TECHNICAL_ASSERTION",
    applicationLoggingRequired: false,
    thresholdProposal: "Alle fire handlinger virker i hver økt uten straff, skjult profil eller gjenoppliving.",
    blocksContinuationWhen: "Én kritisk kontroll ikke virker eller blir overstyrt av systemet.",
  },
  {
    measureId: "B8-MEASURE-05",
    domain: "SAFETY",
    question: "Oppstår ubehag, stigma, barnsliggjøring eller skam?",
    collectionMethod: "STRUCTURED_OBSERVATION",
    applicationLoggingRequired: false,
    thresholdProposal: "Null kritiske hendelser; gjentatt major hendelse pauser piloten.",
    blocksContinuationWhen: "Kritisk stopregel eller to like major-hendelser utløses.",
  },
  {
    measureId: "B8-MEASURE-06",
    domain: "ACCESSIBILITY",
    question: "Kan kritisk flyt gjennomføres med godkjent tastatur-/skjermleseroppsett?",
    collectionMethod: "STRUCTURED_OBSERVATION",
    applicationLoggingRequired: false,
    thresholdProposal: "Ingen kritisk blokkering i start, hjelp, pause, stopp eller voksenkort.",
    blocksContinuationWhen: "En kritisk handling er utilgjengelig.",
  },
  {
    measureId: "B8-MEASURE-10",
    domain: "ADULT_WORKLOAD",
    question: "Kan voksen forstå, vente, avvise eller handle på ett kort uten å miste barnet?",
    collectionMethod: "STRUCTURED_OBSERVATION",
    applicationLoggingRequired: false,
    thresholdProposal: "Minst N-1 voksne handler eller avviser innen foreslått 20-sekunders vindu; terskelen fryses etter adult-only dry-run.",
    blocksContinuationWhen: "Kortet krever lang lesing, kommer for ofte eller overstyrer faglig skjønn.",
  },
];

export const b8ReadinessDossier: B8ReadinessDossier = {
  dossierId: "b8-readiness.wp13-4.v1",
  revision: 1,
  generatedOn: "2026-07-14",
  ownerDecisionStatus: "NOT_TAKEN",
  requirements,
  stopRules,
  reopenSignals,
  candidateEnvelope: {
    status: "PROPOSED_NOT_AUTHORIZED",
    ageBand: "6-9",
    mode: "GUIDED_DYAD_TEACHER",
    siteCountMaximum: 1,
    dyadCountMinimum: 6,
    dyadCountMaximum: 8,
    sessionsPerDyadMaximum: 1,
    sessionMinutesMaximum: 20,
    activityIds: ["activity.word-build.sol-mus.v1"],
    applicationDataPolicy: "SESSION_ONLY_DELETE_AT_END",
    evaluationRecordPolicy: "SEPARATE_STRUCTURED_FORM_RANDOM_CODE",
    audioCapture: false,
    freeTextInApplication: false,
    runtimeAi: false,
    crossSessionProfile: false,
    remoteHomeUse: false,
  },
  measurementRules,
};

export const b8SourceRegister = [
  {
    sourceId: "SRC-UDIR-SCHOOL-OWNER",
    title: "Barnehage- og skoleeiers personvernansvar",
    authority: "Utdanningsdirektoratet",
    checkedOn: "2026-07-14",
    use: "Skoleeier må sørge for og dokumentere at personvernkravene er oppfylt.",
  },
  {
    sourceId: "SRC-UDIR-PERSONAL-DATA",
    title: "Behandle personopplysninger",
    authority: "Utdanningsdirektoratet",
    checkedOn: "2026-07-14",
    use: "Behandlingsgrunnlag, ansvar og daglig etterlevelse i skolekontekst.",
  },
  {
    sourceId: "SRC-DT-DPIA",
    title: "Vurdering av personvernkonsekvenser",
    authority: "Datatilsynet",
    checkedOn: "2026-07-14",
    use: "DPIA kreves når behandlingen sannsynligvis medfører høy risiko.",
  },
  {
    sourceId: "SRC-DT-SCHOOL-AUDIT",
    title: "Funn fra tilsyn med personvernet i skolen",
    authority: "Datatilsynet",
    checkedOn: "2026-07-14",
    use: "Digitale læringsverktøy må vurderes og dokumenteres bedre før bruk.",
  },
  {
    sourceId: "SRC-UDIR-AI-PRIVACY",
    title: "Ta hensyn til personvernet ved bruk av KI",
    authority: "Utdanningsdirektoratet",
    checkedOn: "2026-07-14",
    use: "KI-løsninger i undervisningen må være godkjent og personvernvurdert av skoleeier.",
  },
  {
    sourceId: "SRC-NESH-CONSENT",
    title: "Uttalelse om passivt samtykke i Ungdata",
    authority: "De nasjonale forskningsetiske komiteene / NESH",
    checkedOn: "2026-07-14",
    use: "Aktivt, frivillig, informert og uttrykkelig samtykke er hovedregelen; barn skal informeres og kunne avstå.",
  },
  {
    sourceId: "SRC-EU-AI-ACT",
    title: "AI Act — application timeline and official guidance",
    authority: "European Commission",
    checkedOn: "2026-07-14",
    use: "Regelverksstatus må kontrolleres på nytt før eventuell AI-funksjon eller produktpåstand.",
  },
] as const;
