import type { Localized } from "../../core/skynja/exercise-room.js";
import { arrange, bi, exercise } from "./exercise-authoring.js";

function word(id: string, target: Localized<string>, meaning: Localized<string>, hint: Localized<string>, explanation: Localized<string>, reflection: Localized<string>) {
  return arrange({ id, prompt: bi("Bygg ordet med bokstavbrikkene. Ordet står her som støtte.", "Bygg ordet med bokstavbrikkene. Ordet står her som støtte."),
    stimulus: bi(`${target["nb-NO"]}\n${meaning["nb-NO"]}`, `${target["nn-NO"]}\n${meaning["nn-NO"]}`),
    pieces: bi([...target["nb-NO"]].reverse(), [...target["nn-NO"]].reverse()), answers: bi([target["nb-NO"]], [target["nn-NO"]]), joiner: "",
    hint, explanation, reflection });
}

function compound(id: string, target: Localized<string>, pieces: Localized<readonly string[]>, meaning: Localized<string>, hint: Localized<string>, explanation: Localized<string>, reflection: Localized<string>) {
  return arrange({ id, prompt: bi("Sett de to delene sammen til ett ord som passer til forklaringen.", "Set dei to delane saman til eitt ord som passar til forklaringa."),
    stimulus: meaning, pieces, answers: bi([target["nb-NO"]], [target["nn-NO"]]), joiner: "", hint, explanation, reflection });
}

function sentence(id: string, target: Localized<string>, pieces: Localized<readonly string[]>, stimulus: Localized<string>, hint: Localized<string>, explanation: Localized<string>, reflection: Localized<string>) {
  return arrange({ id, prompt: bi("Bygg setningen. Begynn med brikken som har stor bokstav, og avslutt med punktum.", "Bygg setninga. Byrj med brikka som har stor bokstav, og avslutt med punktum."),
    stimulus, pieces, answers: bi([target["nb-NO"]], [target["nn-NO"]]), joiner: " ", hint, explanation, reflection });
}

export const buildingExercises = [
  exercise({ id: "skynja-maane-saape", kind: "WORD", sourceActivityId: "activity-nor-two-syllable-maane-saape-001",
    title: bi("Måne og såpe", "Måne og såpe"),
    summary: bi("Bygg fem ord med å. Se på bokstavene og snakk om hva ordene betyr.", "Bygg fem ord med å. Sjå på bokstavane og snakk om kva orda tyder."),
    purpose: bi("Utforske bokstavrekkefølge med et synlig ord som modell. Du kan se på hele ordet mens du bygger.", "Utforske bokstavrekkjefølgje med eit synleg ord som modell. Du kan sjå på heile ordet medan du byggjer."),
    observe: bi("Spør hvilken støtte som er ønsket: peke på en bokstav, vise rekkefølgen eller lese ordet sammen. Å kopiere modellen viser ikke at ordet kan leses uten støtte.", "Spør kva støtte som er ønskt: peike på ein bokstav, vise rekkjefølgja eller lese ordet saman. Å kopiere modellen viser ikkje at ordet kan lesast utan støtte."),
    transfer: bi("Velg et av ordene og lag en muntlig setning. Finn gjerne ordet i en tekst sammen; det er en ny situasjon, ikke en test av overføring.", "Vel eit av orda og lag ei munnleg setning. Finn gjerne ordet i ein tekst saman; det er ein ny situasjon, ikkje ein test av overføring."),
    rounds: [
      word("maane", bi("måne", "måne"), bi("Vi så en lys måne på himmelen.", "Vi såg ein lys måne på himmelen."), bi("Finn m først. Så kommer å, n og e.", "Finn m først. Så kjem å, n og e."), bi("m–å–n–e blir måne. Bokstaven å står som nummer to.", "m–å–n–e blir måne. Bokstaven å står som nummer to."), bi("Hva legger du merke til ved å sammenlignet med a?", "Kva legg du merke til ved å samanlikna med a?")),
      word("saape", bi("såpe", "såpe"), bi("Det ligger en såpe ved vasken.", "Det ligg ei såpe ved vasken."), bi("Begynn med s. Se deretter på de tre siste bokstavene.", "Byrj med s. Sjå deretter på dei tre siste bokstavane."), bi("s–å–p–e blir såpe. Måne og såpe har å på samme plass, men ulike konsonanter.", "s–å–p–e blir såpe. Måne og såpe har å på same plass, men ulike konsonantar."), bi("Hvilke bokstaver er like i måne og såpe?", "Kva bokstavar er like i måne og såpe?")),
      word("laave", bi("låve", "låve"), bi("På gården står en rød låve.", "På garden står ein raud låve."), bi("Den første bokstaven er l. Ordet slutter med ve.", "Den første bokstaven er l. Ordet sluttar med ve."), bi("l–å–v–e blir låve. Ordet begynner med l og slutter med e.", "l–å–v–e blir låve. Ordet byrjar med l og sluttar med e."), bi("Kan du peke på v og si hvor den står?", "Kan du peike på v og seie kvar han står?")),
      word("kaape", bi("kåpe", "kåpe"), bi("Hun henger en kåpe på knaggen.", "Ho heng ei kåpe på knaggen."), bi("Se på k først. De tre siste bokstavene er åpe.", "Sjå på k først. Dei tre siste bokstavane er åpe."), bi("k–å–p–e blir kåpe. Kåpe og såpe skiller seg i den første bokstaven.", "k–å–p–e blir kåpe. Kåpe og såpe skil seg i den første bokstaven."), bi("Hva skjer med betydningen når s i såpe blir byttet med k?", "Kva skjer med tydinga når s i såpe blir bytt med k?")),
      word("taake", bi("tåke", "tåke"), bi("Det er tåke, så vi ser ikke huset langt borte.", "Det er tåke, så vi ser ikkje huset langt borte."), bi("Start med t. Se etter k før den siste e-en.", "Start med t. Sjå etter k før den siste e-en."), bi("t–å–k–e blir tåke. Her står k inne i ordet, ikke først som i kåpe.", "t–å–k–e blir tåke. Her står k inne i ordet, ikkje først som i kåpe."), bi("Velg et av de fem ordene. Hva hjalp deg å bygge det?", "Vel eit av dei fem orda. Kva hjelpte deg å byggje det?")),
    ] }),
  exercise({ id: "skynja-kake-bake", kind: "WORD", sourceActivityId: "activity-nor-two-syllable-kake-bake-002",
    title: bi("Kake og bake", "Kake og bake"),
    summary: bi("Bygg fem korte ord. Se hvordan små endringer gir nye ord og betydninger.", "Bygg fem korte ord. Sjå korleis små endringar gir nye ord og tydingar."),
    purpose: bi("Sammenligne bokstaver og rekkefølge med en synlig modell. Betydningen følger med i en setning.", "Samanlikne bokstavar og rekkjefølgje med ein synleg modell. Tydinga følgjer med i ei setning."),
    observe: bi("La begge like bokstavbrikker kunne brukes om hverandre. Tilby å bygge sammen. Et ferdig ord sier ikke hvilken lesestrategi personen brukte.", "La begge like bokstavbrikker kunne brukast om kvarandre. Tilby å byggje saman. Eit ferdig ord seier ikkje kva lesestrategi personen brukte."),
    transfer: bi("Velg to ord og forklar forskjellen med en tegning, en setning eller en samtale.", "Vel to ord og forklar skilnaden med ei teikning, ei setning eller ein samtale."),
    rounds: [
      word("kake", bi("kake", "kake"), bi("Vi deler en kake ved bordet.", "Vi deler ei kake ved bordet."), bi("Du trenger begge k-brikkene: én først og én etter a.", "Du treng begge k-brikkene: éi først og éi etter a."), bi("k–a–k–e blir kake. Det er to k-er i ordet, med a mellom.", "k–a–k–e blir kake. Det er to k-ar i ordet, med a mellom."), bi("Kan du finne begge k-ene i modellen?", "Kan du finne begge k-ane i modellen?")),
      word("bake", bi("bake", "bake"), bi("Vi vil bake noe til turen.", "Vi vil bake noko til turen."), bi("Begynn med b. Resten er ake, akkurat som i kake.", "Byrj med b. Resten er ake, akkurat som i kake."), bi("b–a–k–e blir bake. Kake er noe vi kan spise; bake beskriver noe vi gjør.", "b–a–k–e blir bake. Kake er noko vi kan ete; bake skildrar noko vi gjer."), bi("Hvordan endret første bokstav både ordet og betydningen?", "Korleis endra første bokstav både ordet og tydinga?")),
      word("male", bi("male", "male"), bi("Vi skal male en blå dør.", "Vi skal male ei blå dør."), bi("Finn m først. Sett l mellom a og e.", "Finn m først. Set l mellom a og e."), bi("m–a–l–e blir male. I denne setningen betyr male å legge på maling.", "m–a–l–e blir male. I denne setninga tyder male å leggje på måling."), bi("Hva i setningen hjelper deg å forstå ordet male?", "Kva i setninga hjelper deg å forstå ordet male?")),
      word("tale", bi("tale", "tale"), bi("Hun skal holde en tale i selskapet.", "Ho skal halde ein tale i selskapet."), bi("Bytt m fra male med t. De tre siste bokstavene er like.", "Byt m frå male med t. Dei tre siste bokstavane er like."), bi("t–a–l–e blir tale. I setningen er en tale noe noen sier til en gruppe.", "t–a–l–e blir tale. I setninga er ein tale noko nokon seier til ei gruppe."), bi("Hvilke tre bokstaver er felles i male og tale?", "Kva tre bokstavar er felles i male og tale?")),
      word("rake", bi("rake", "rake"), bi("Vi skal rake løv i hagen.", "Vi skal rake lauv i hagen."), bi("Ordet begynner med r og slutter med ake.", "Ordet byrjar med r og sluttar med ake."), bi("r–a–k–e blir rake. Rake, bake og kake har de tre siste bokstavene felles.", "r–a–k–e blir rake. Rake, bake og kake har dei tre siste bokstavane felles."), bi("Vil du si ordene, peke på det som er likt, eller få noen til å lese dem?", "Vil du seie orda, peike på det som er likt, eller få nokon til å lese dei?")),
    ] }),
  exercise({ id: "skynja-compound-home", kind: "COMPOUND",
    title: bi("To deler blir ett ord", "To delar blir eitt ord"),
    summary: bi("Sett sammen ord for ting du kan ha hjemme eller ta med ut.", "Set saman ord for ting du kan ha heime eller ta med ut."),
    purpose: bi("Utforske hvordan to kjente ord kan danne ett nytt ord. Forklaringen hjelper deg å velge rekkefølge.", "Utforske korleis to kjende ord kan danne eitt nytt ord. Forklaringa hjelper deg å velje rekkjefølgje."),
    observe: bi("Les delene sammen ved behov. Spør hva hele ordet betyr. Et riktig brikkevalg alene viser ikke at personen kjenner ordet fra før.", "Les delane saman ved behov. Spør kva heile ordet tyder. Eit rett brikkeval åleine viser ikkje at personen kjenner ordet frå før."),
    transfer: bi("Finn en sammensatt betegnelse på en ting i nærheten. Undersøk sammen hvilke deler ordet har.", "Finn ei samansett nemning på ein ting i nærleiken. Undersøk saman kva delar ordet har."),
    rounds: [
      compound("matboks", bi("matboks", "matboks"), bi(["boks", "mat"], ["boks", "mat"]), bi("En boks til å ha mat i.", "Ein boks til å ha mat i."), bi("Det er en slags boks. Boks står sist.", "Det er ein slags boks. Boks står sist."), bi("Mat + boks blir matboks. Den siste delen forteller hva slags ting det er.", "Mat + boks blir matboks. Den siste delen fortel kva slags ting det er."), bi("Hva forteller den første delen om boksen?", "Kva fortel den første delen om boksen?")),
      compound("bokhylle", bi("bokhylle", "bokhylle"), bi(["hylle", "bok"], ["hylle", "bok"]), bi("En hylle til bøker.", "Ei hylle til bøker."), bi("Hvilken del sier hva slags møbel dette er? Sett den sist.", "Kva del seier kva slags møbel dette er? Set han sist."), bi("Bok + hylle blir bokhylle. Bok forteller hva hyllen brukes til.", "Bok + hylle blir bokhylle. Bok fortel kva hylla blir brukt til."), bi("Kan en bokhylle også inneholde andre ting enn bøker?", "Kan ei bokhylle òg innehalde andre ting enn bøker?")),
      compound("solbriller", bi("solbriller", "solbriller"), bi(["briller", "sol"], ["briller", "sol"]), bi("Briller som skjermer øynene mot sterkt sollys.", "Briller som skjermar auga mot sterkt sollys."), bi("Det er briller. Sett sol foran briller.", "Det er briller. Set sol framfor briller."), bi("Sol + briller blir solbriller. Ordet skrives samlet.", "Sol + briller blir solbriller. Ordet blir skrive samla."), bi("Hvorfor gir det mening at briller er siste del?", "Kvifor gir det meining at briller er siste del?")),
      compound("regnjakke", bi("regnjakke", "regnjakke"), bi(["jakke", "regn"], ["jakke", "regn"]), bi("En jakke du kan bruke når det regner.", "Ei jakke du kan bruke når det regnar."), bi("Start med været, og avslutt med plagget.", "Start med vêret, og avslutt med plagget."), bi("Regn + jakke blir regnjakke. Delene hjelper oss å forstå hele ordet.", "Regn + jakke blir regnjakke. Delane hjelper oss å forstå heile ordet."), bi("Hvilken av de to delene var lettest å finne fram til?", "Kva av dei to delane var lettast å finne fram til?")),
    ] }),
  exercise({ id: "skynja-compound-outside", kind: "COMPOUND",
    title: bi("Ord på vei", "Ord på veg"),
    summary: bi("Bygg fire sammensatte ord fra turer, reiser og hverdagen.", "Bygg fire samansette ord frå turar, reiser og kvardagen."),
    purpose: bi("Bruke betydningen av orddeler til å undersøke lengre ord. Du kan få delene lest høyt av en person.", "Bruke tydinga av orddelar til å undersøkje lengre ord. Du kan få delane lesne høgt av ein person."),
    observe: bi("Lengre ord trenger ikke være vanskeligere for alle. Spør om ordene er kjente, og forklar sammenhengen før dere vurderer et svar.", "Lengre ord treng ikkje vere vanskelegare for alle. Spør om orda er kjende, og forklar samanhengen før de vurderer eit svar."),
    transfer: bi("Let etter et sammensatt ord på et skilt eller en gjenstand. Det er lov å få hele ordet forklart.", "Leit etter eit samansett ord på eit skilt eller ein gjenstand. Det er lov å få heile ordet forklart."),
    rounds: [
      compound("sykkelhjelm", bi("sykkelhjelm", "sykkelhjelm"), bi(["hjelm", "sykkel"], ["hjelm", "sykkel"]), bi("En hjelm til bruk når du sykler.", "Ein hjelm til bruk når du syklar."), bi("Hjelm forteller hva tingen er. Sett hjelm sist.", "Hjelm fortel kva tingen er. Set hjelm sist."), bi("Sykkel + hjelm blir sykkelhjelm. To deler danner ett ord, selv om ordet er langt.", "Sykkel + hjelm blir sykkelhjelm. To delar dannar eitt ord, sjølv om ordet er langt."), bi("Hvilken del sier noe om bruken?", "Kva del seier noko om bruken?")),
      compound("busskort", bi("busskort", "busskort"), bi(["kort", "buss"], ["kort", "buss"]), bi("Et kort som brukes til bussreiser.", "Eit kort som blir brukt til bussreiser."), bi("Start med buss. Behold begge s-ene i den delen.", "Start med buss. Hald på begge s-ane i den delen."), bi("Buss + kort blir busskort. Bokstavene fra begge delene er med.", "Buss + kort blir busskort. Bokstavane frå begge delane er med."), bi("Hvor går grensen mellom de to delene?", "Kvar går grensa mellom dei to delane?")),
      compound("skolesekk", bi("skolesekk", "skulesekk"), bi(["sekk", "skole"], ["sekk", "skule"]), bi("En sekk til det du trenger på skolen.", "Ein sekk til det du treng på skulen."), bi("Skole kommer først. Sekk kommer sist.", "Skule kjem først. Sekk kjem sist."), bi("Skole + sekk blir skolesekk. På nynorsk kan du møte formen skulesekk.", "Skule + sekk blir skulesekk. På bokmål kan du møte forma skolesekk."), bi("Hvilke ord bruker du selv om en slik sekk?", "Kva ord bruker du sjølv om ein slik sekk?")),
      compound("tursti", bi("tursti", "tursti"), bi(["sti", "tur"], ["sti", "tur"]), bi("En sti som brukes til å gå tur.", "Ein sti som blir brukt til å gå tur."), bi("Ordet beskriver en sti. Sti blir siste del.", "Ordet skildrar ein sti. Sti blir siste del."), bi("Tur + sti blir tursti. Her er de to delene korte, men de danner også et sammensatt ord.", "Tur + sti blir tursti. Her er dei to delane korte, men dei dannar òg eit samansett ord."), bi("Hvordan kan du bruke delene når du møter et nytt langt ord?", "Korleis kan du bruke delane når du møter eit nytt langt ord?")),
    ] }),
  exercise({ id: "skynja-sentences-everyday", kind: "SENTENCE",
    title: bi("Hvem gjør hva?", "Kven gjer kva?"),
    summary: bi("Sett ordbrikker i rekkefølge og bygg fire korte setninger.", "Set ordbrikker i rekkjefølgje og bygg fire korte setningar."),
    purpose: bi("Utforske hvordan ordrekkefølge skaper mening. Stor bokstav og punktum viser starten og slutten i disse oppgavene.", "Utforske korleis ordrekkjefølgje skaper meining. Stor bokstav og punktum viser starten og slutten i desse oppgåvene."),
    observe: bi("La personen høre eller si hele setningen hvis det er ønsket. Det kan støtte arbeidet med rekkefølge; det er ikke selvstendig lesing.", "La personen høyre eller seie heile setninga dersom det er ønskt. Det kan støtte arbeidet med rekkjefølgje; det er ikkje sjølvstendig lesing."),
    transfer: bi("Lag en ny muntlig setning ved å bytte ut én av personene eller handlingene.", "Lag ei ny munnleg setning ved å byte ut ein av personane eller ei av handlingane."),
    rounds: [
      sentence("ida-reads", bi("Ida leser boka.", "Ida les boka."), bi(["boka.", "Ida", "leser"], ["boka.", "Ida", "les"]), bi("Ida har en bok. Setningen skal fortelle hva Ida gjør.", "Ida har ei bok. Setninga skal fortelje kva Ida gjer."), bi("Start med Ida. Sett handlingen leser etter navnet.", "Start med Ida. Set handlinga les etter namnet."), bi("Ida leser boka. Ida er den som gjør noe; leser beskriver handlingen.", "Ida les boka. Ida er den som gjer noko; les skildrar handlinga."), bi("Hvilken brikke forteller hva Ida gjør?", "Kva brikke fortel kva Ida gjer?")),
      sentence("we-find", bi("Vi finner nøkkelen.", "Vi finn nøkkelen."), bi(["finner", "nøkkelen.", "Vi"], ["finn", "nøkkelen.", "Vi"]), bi("Nøkkelen var borte. Nå skal setningen fortelle at vi finner den.", "Nøkkelen var borte. No skal setninga fortelje at vi finn han."), bi("Vi skal stå først. Nøkkelen avslutter setningen.", "Vi skal stå først. Nøkkelen avsluttar setninga."), bi("Vi finner nøkkelen. Rekkefølgen viser hvem som finner, og hva de finner.", "Vi finn nøkkelen. Rekkjefølgja viser kven som finn, og kva dei finn."), bi("Hvordan endres betydningen hvis nøkkelen blir byttet ut med sekken?", "Korleis blir tydinga endra dersom nøkkelen blir bytt ut med sekken?")),
      sentence("amir-packs", bi("Amir pakker en sekk.", "Amir pakkar ein sekk."), bi(["en", "sekk.", "pakker", "Amir"], ["ein", "sekk.", "pakkar", "Amir"]), bi("Amir gjør seg klar til tur. Lag en setning om det han pakker.", "Amir gjer seg klar til tur. Lag ei setning om det han pakkar."), bi("Start med Amir pakker. En står rett foran sekk.", "Start med Amir pakkar. Ein står rett framfor sekk."), bi("Amir pakker en sekk. En og sekk hører sammen i denne setningen.", "Amir pakkar ein sekk. Ein og sekk høyrer saman i denne setninga."), bi("Hvilke to brikker ville du holde sammen?", "Kva to brikker ville du halde saman?")),
      sentence("cat-sleeps", bi("Katten sover på stolen.", "Katten søv på stolen."), bi(["stolen.", "på", "Katten", "sover"], ["stolen.", "på", "Katten", "søv"]), bi("Katten har funnet et sted å sove. Fortell både hva den gjør og hvor den er.", "Katten har funne ein stad å sove. Fortel både kva han gjer og kvar han er."), bi("Katten kommer først. På stolen skal stå sammen til slutt.", "Katten kjem først. På stolen skal stå saman til slutt."), bi("Katten sover på stolen. På stolen gir ekstra informasjon om stedet.", "Katten søv på stolen. På stolen gir ekstra informasjon om staden."), bi("Hva får vi vite hvis vi bare sier Katten sover? Hva mangler da?", "Kva får vi vite dersom vi berre seier Katten søv? Kva manglar då?")),
    ] }),
  exercise({ id: "skynja-sentences-messages", kind: "SENTENCE",
    title: bi("Små beskjeder", "Små beskjedar"),
    summary: bi("Bygg setninger du kan bruke når du trenger tid, hjelp eller en avklaring.", "Bygg setningar du kan bruke når du treng tid, hjelp eller ei avklaring."),
    purpose: bi("Arbeide med ordrekkefølge i meningsfulle beskjeder. Du velger selv om noen av formuleringene passer for deg.", "Arbeide med ordrekkjefølgje i meiningsfulle beskjedar. Du vel sjølv om nokon av formuleringane passar for deg."),
    observe: bi("Formuleringene er eksempler, ikke krav til hvordan en person må be om støtte. Peking, skrift, tale og andre uttrykk kan også fungere.", "Formuleringane er døme, ikkje krav til korleis ein person må be om støtte. Peiking, skrift, tale og andre uttrykk kan òg fungere."),
    transfer: bi("Velg en beskjed og gjør den mer naturlig med dine egne ord. Den trenger ikke lagres eller deles.", "Vel ein beskjed og gjer han meir naturleg med dine eigne ord. Han treng ikkje lagrast eller delast."),
    rounds: [
      sentence("need-time", bi("Jeg trenger litt tid.", "Eg treng litt tid."), bi(["litt", "tid.", "Jeg", "trenger"], ["litt", "tid.", "Eg", "treng"]), bi("Lag en beskjed om å få tid til å tenke.", "Lag ein beskjed om å få tid til å tenkje."), bi("Start med Jeg trenger. Litt forteller noe om tiden.", "Start med Eg treng. Litt fortel noko om tida."), bi("Jeg trenger litt tid. Beskjeden ber om rom til å fortsette i eget tempo.", "Eg treng litt tid. Beskjeden ber om rom til å halde fram i eige tempo."), bi("Hvordan kunne du sagt eller vist det samme på din måte?", "Korleis kunne du sagt eller vist det same på din måte?")),
      sentence("read-together", bi("Vi kan lese sammen.", "Vi kan lese saman."), bi(["lese", "sammen.", "kan", "Vi"], ["lese", "saman.", "kan", "Vi"]), bi("Lag et forslag om å dele på lesingen.", "Lag eit forslag om å dele på lesinga."), bi("Vi kan kommer først. Lese sammen avslutter setningen.", "Vi kan kjem først. Lese saman avsluttar setninga."), bi("Vi kan lese sammen. Kan gjør dette til en mulighet, ikke et pålegg.", "Vi kan lese saman. Kan gjer dette til eit høve, ikkje eit pålegg."), bi("Når kunne det være nyttig å dele på lesingen?", "Når kunne det vere nyttig å dele på lesinga?")),
      sentence("show-start", bi("Vis meg den første delen.", "Vis meg den første delen."), bi(["første", "Vis", "delen.", "den", "meg"], ["første", "Vis", "delen.", "den", "meg"]), bi("Lag en beskjed om å få se starten av en oppgave.", "Lag ein beskjed om å få sjå starten av ei oppgåve."), bi("Start med Vis meg. Den første delen hører sammen.", "Start med Vis meg. Den første delen høyrer saman."), bi("Vis meg den første delen. Beskjeden sier konkret hvilken støtte som ønskes.", "Vis meg den første delen. Beskjeden seier konkret kva støtte som er ønskt."), bi("Hva kunne første del være i en oppgave du kjenner?", "Kva kunne første del vere i ei oppgåve du kjenner?")),
      sentence("pause-now", bi("Jeg vil ta en pause.", "Eg vil ta ein pause."), bi(["pause.", "vil", "Jeg", "en", "ta"], ["pause.", "vil", "Eg", "ein", "ta"]), bi("Lag en tydelig beskjed om pause.", "Lag ein tydeleg beskjed om pause."), bi("Begynn med Jeg vil. Ta en pause står til slutt.", "Byrj med Eg vil. Ta ein pause står til slutt."), bi("Jeg vil ta en pause. Man trenger ikke gjøre ferdig en runde for å bruke pauseknappen.", "Eg vil ta ein pause. Ein treng ikkje gjere ferdig ein runde for å bruke pauseknappen."), bi("Vil du fortsette, se et forslag eller ta en pause nå?", "Vil du halde fram, sjå eit forslag eller ta ein pause no?")),
    ] }),
] as const;
