import { NOT_STATED } from "../../core/skynja/exercise-room.js";
import { bi, evidence, exercise } from "./exercise-authoring.js";

const retry = bi(
  "Svaret ditt passer, men det valgte tekststedet gir ikke grunnlaget vi trenger her. Se etter setningen som svarer på akkurat dette spørsmålet, eller velg at informasjonen mangler.",
  "Svaret ditt passar, men den valde tekststaden gir ikkje grunnlaget vi treng her. Sjå etter setninga som svarar på akkurat dette spørsmålet, eller vel at informasjonen manglar.",
);

export const evidenceExercise = exercise({
  id: "skynja-find-evidence", kind: "EVIDENCE",
  title: bi("Finn tekstbeviset", "Finn tekstbeviset"),
  summary: bi("Velg et svar og finn setningen som støtter det. Noen ganger mangler teksten informasjon.", "Vel eit svar og finn setninga som støttar det. Somme gonger manglar teksten informasjon."),
  purpose: bi("Koble et svar til det som faktisk står i teksten. Utforsk direkte opplysninger, rimelige slutninger og spørsmål teksten ikke avgjør.", "Kople eit svar til det som faktisk står i teksten. Utforsk direkte opplysningar, rimelege slutningar og spørsmål teksten ikkje avgjer."),
  observe: bi("Alle situasjonene er oppdiktet. Les sammen ved behov. Et svar og et valgt tekststed er to separate handlinger; ingen av dem beviser selvstendig lesing eller generell kildekritisk kompetanse.", "Alle situasjonane er oppdikta. Les saman ved behov. Eit svar og ein vald tekststad er to separate handlingar; ingen av dei beviser sjølvstendig lesing eller generell kjeldekritisk kompetanse."),
  transfer: bi("Ta en beskjed uten private opplysninger. Finn ett svar, pek på tekststedet som støtter det, og si hva beskjeden fortsatt ikke forteller.", "Ta ein beskjed utan private opplysningar. Finn eitt svar, peik på tekststaden som støttar det, og sei kva beskjeden framleis ikkje fortel."),
  rounds: [
    evidence({ id: "evidence-meeting", prompt: bi("Hvor skal gruppen møtes?", "Kvar skal gruppa møtast?"),
      stimulus: bi("En oppdiktet beskjed om en tur:", "Ein oppdikta beskjed om ein tur:"),
      passages: [
        { id: "meeting-time", text: bi("Turen begynner tirsdag klokka 17.", "Turen byrjar tysdag klokka 17.") },
        { id: "meeting-place", text: bi("Vi møtes ved hovedinngangen til biblioteket.", "Vi møtest ved hovudinngangen til biblioteket.") },
        { id: "meeting-end", text: bi("Turen slutter ved den gamle brua.", "Turen sluttar ved den gamle brua.") },
      ],
      options: [
        { label: bi("Ved den gamle brua", "Ved den gamle brua"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Brua er stedet turen slutter. Spørsmålet gjelder hvor gruppen møtes.", "Brua er staden turen sluttar. Spørsmålet gjeld kvar gruppa møtest.") },
        { label: bi("Ved hovedinngangen til biblioteket", "Ved hovudinngangen til biblioteket"), verdict: "MATCHED", evidenceIds: ["meeting-place"], feedback: bi("Svaret og tekststedet passer sammen. Setningen med «Vi møtes» oppgir møteplassen direkte.", "Svaret og tekststaden passar saman. Setninga med «Vi møtest» oppgir møteplassen direkte.") },
        { label: bi("Det står ikke hvor de møtes", "Det står ikkje kvar dei møtest"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Denne beskjeden oppgir møteplassen. Se etter verbet møtes.", "Denne beskjeden oppgir møteplassen. Sjå etter verbet møtest.") },
      ],
      hint: bi("Se etter møtes. Tidspunktet og sluttstedet svarer på andre spørsmål.", "Sjå etter møtest. Tidspunktet og sluttstaden svarar på andre spørsmål."),
      model: bi("Svar: Hovedinngangen til biblioteket. Tekstbevis: «Vi møtes ved hovedinngangen til biblioteket.»", "Svar: Hovudinngangen til biblioteket. Tekstbevis: «Vi møtest ved hovudinngangen til biblioteket.»"),
      explanation: bi("Et tekststed kan være sant og likevel ikke støtte svaret på spørsmålet. Her trenger vi møteplassen, ikke sluttstedet.", "Ein tekststad kan vere sann og likevel ikkje støtte svaret på spørsmålet. Her treng vi møteplassen, ikkje sluttstaden."),
      reflection: bi("Hva ville du ha lett etter dersom spørsmålet gjaldt når turen begynner?", "Kva ville du ha leita etter dersom spørsmålet gjaldt når turen byrjar?"), evidenceRetry: retry,
    }),
    evidence({ id: "evidence-condition", prompt: bi("Hvor foregår samlingen hvis det regner?", "Kvar går samlinga føre seg dersom det regnar?"),
      stimulus: bi("Planen for en oppdiktet samling:", "Planen for ei oppdikta samling:"),
      passages: [
        { id: "condition-dry", text: bi("Hvis det er opphold, sitter vi i hagen.", "Dersom det er opphald, sit vi i hagen.") },
        { id: "condition-rain", text: bi("Hvis det regner, flytter vi inn i møterommet.", "Dersom det regnar, flyttar vi inn i møterommet.") },
        { id: "condition-time", text: bi("Samlingen begynner klokka 12 uansett vær.", "Samlinga byrjar klokka 12 uansett vêr.") },
      ],
      options: [
        { label: bi("I møterommet", "I møterommet"), verdict: "MATCHED", evidenceIds: ["condition-rain"], feedback: bi("Tekststedet nevner både regn og stedet de flytter til. Det støtter svaret ditt.", "Tekststaden nemner både regn og staden dei flyttar til. Det støttar svaret ditt.") },
        { label: bi("I hagen uansett vær", "I hagen uansett vêr"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Hagen gjelder når det er opphold. Spørsmålet beskriver regn.", "Hagen gjeld når det er opphald. Spørsmålet skildrar regn.") },
        { label: bi("Samlingen blir avlyst", "Samlinga blir avlyst"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Planen sier at samlingen flyttes inn ved regn, ikke at den avlyses.", "Planen seier at samlinga blir flytta inn ved regn, ikkje at ho blir avlyst.") },
      ],
      hint: bi("Finn setningen der betingelsen er den samme som i spørsmålet.", "Finn setninga der vilkåret er det same som i spørsmålet."),
      model: bi("Svar: I møterommet. Tekstbevis: «Hvis det regner, flytter vi inn i møterommet.»", "Svar: I møterommet. Tekstbevis: «Dersom det regnar, flyttar vi inn i møterommet.»"),
      explanation: bi("Et hvis-uttrykk gjelder en bestemt situasjon. Et svar om hagen kan passe til opphold, men ikke til regnet i spørsmålet.", "Eit dersom-uttrykk gjeld ein bestemt situasjon. Eit svar om hagen kan passe til opphald, men ikkje til regnet i spørsmålet."),
      reflection: bi("Hva i teksten gjelder både ved regn og opphold?", "Kva i teksten gjeld både ved regn og opphald?"), evidenceRetry: retry,
    }),
    evidence({ id: "evidence-inference", prompt: bi("Hvorfor tar Ada sannsynligvis med en lommelykt?", "Kvifor tek Ada truleg med ei lommelykt?"),
      stimulus: bi("En kort, oppdiktet fortelling:", "Ei kort, oppdikta forteljing:"),
      passages: [
        { id: "inference-bag", text: bi("Ada legger en lommelykt i sekken før turen.", "Ada legg ei lommelykt i sekken før turen.") },
        { id: "inference-dark", text: bi("Gruppen skal gå hjem etter at det har blitt mørkt.", "Gruppa skal gå heim etter at det har blitt mørkt.") },
        { id: "inference-food", text: bi("Alle har med matpakke og vann.", "Alle har med matpakke og vatn.") },
      ],
      options: [
        { label: bi("For å vise at sekken er stor", "For å vise at sekken er stor"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Teksten sier ikke at størrelsen på sekken er viktig. Hjemturen i mørket gir en nærmere forklaring.", "Teksten seier ikkje at storleiken på sekken er viktig. Heimturen i mørket gir ei nærare forklaring.") },
        { label: bi("Fordi gruppen skal spise inne i en hule", "Fordi gruppa skal ete inne i ei hole"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Ingen hule er nevnt. Det blir en ny opplysning vi selv legger til.", "Inga hole er nemnd. Det blir ei ny opplysning vi sjølve legg til.") },
        { label: bi("For å kunne lyse på hjemveien", "For å kunne lyse på heimvegen"), verdict: "REASONABLE", evidenceIds: ["inference-dark"], feedback: bi("Mørket på hjemveien støtter denne forklaringen. Ada sier ikke selv hvorfor, så dette er en rimelig slutning.", "Mørket på heimvegen støttar denne forklaringa. Ada seier ikkje sjølv kvifor, så dette er ei rimeleg slutning.") },
      ],
      hint: bi("Setningen om sekken viser hva Ada gjør. Hvilken annen setning kan forklare hvorfor?", "Setninga om sekken viser kva Ada gjer. Kva anna setning kan forklare kvifor?"),
      model: bi("Svar: Sannsynligvis for å lyse på hjemveien. Grunnlag: Gruppen skal gå hjem etter at det har blitt mørkt.", "Svar: Truleg for å lyse på heimvegen. Grunnlag: Gruppa skal gå heim etter at det har blitt mørkt."),
      explanation: bi("Vi kobler lommelykten til mørket. Teksten støtter slutningen, men bekrefter ikke sikkert hva Ada tenker.", "Vi koplar lommelykta til mørket. Teksten støttar slutninga, men stadfestar ikkje sikkert kva Ada tenkjer."),
      reflection: bi("Hvordan kunne teksten ha sagt grunnen direkte?", "Korleis kunne teksten ha sagt grunnen direkte?"), evidenceRetry: retry,
    }),
    evidence({ id: "evidence-price", prompt: bi("Hva koster det å delta?", "Kva kostar det å delta?"),
      stimulus: bi("En oppdiktet plakat om et verksted:", "Ein oppdikta plakat om ein verkstad:"),
      passages: [
        { id: "price-day", text: bi("Skriveverkstedet er på biblioteket lørdag klokka 11.", "Skriveverkstaden er på biblioteket laurdag klokka 11.") },
        { id: "price-bring", text: bi("Ta med en tekst du vil jobbe med.", "Ta med ein tekst du vil jobbe med.") },
        { id: "price-register", text: bi("Du må melde deg på innen torsdag.", "Du må melde deg på innan torsdag.") },
      ],
      options: [
        { label: bi("Det er sikkert gratis", "Det er sikkert gratis"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Stedet alene sier ikke hva det koster. Plakaten oppgir ingen pris.", "Staden åleine seier ikkje kva det kostar. Plakaten oppgir ingen pris.") },
        { label: bi("Prisen står ikke i teksten", "Prisen står ikkje i teksten"), verdict: "NEEDS_CONTEXT", evidenceIds: [NOT_STATED], feedback: bi("Ingen av setningene oppgir pris. Svaret og valget om manglende informasjon passer sammen.", "Ingen av setningane oppgir pris. Svaret og valet om manglande informasjon passar saman.") },
        { label: bi("Det koster 11 kroner", "Det kostar 11 kroner"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Tallet 11 er et klokkeslett. Det er ikke oppgitt som en pris.", "Talet 11 er eit klokkeslett. Det er ikkje oppgitt som ein pris.") },
      ],
      hint: bi("Let etter pris eller betaling. Et tall kan være et klokkeslett eller en dato.", "Leit etter pris eller betaling. Eit tal kan vere eit klokkeslett eller ein dato."),
      model: bi("Svar: Prisen er ikke oppgitt. Grunnlag: Velg «Teksten gir ikke nok informasjon».", "Svar: Prisen er ikkje oppgitt. Grunnlag: Vel «Teksten gir ikkje nok informasjon»."),
      explanation: bi("Vi må spørre arrangøren eller finne en ny beskjed. Manglende prisinformasjon betyr verken gratis eller dyrt.", "Vi må spørje arrangøren eller finne ein ny beskjed. Manglande prisinformasjon tyder korkje gratis eller dyrt."),
      reflection: bi("Hvilket kort spørsmål kunne avklart dette?", "Kva kort spørsmål kunne avklart dette?"), evidenceRetry: retry,
    }),
    evidence({ id: "evidence-update", prompt: bi("Hvilket tidspunkt gjelder etter oppdateringen?", "Kva tidspunkt gjeld etter oppdateringa?"),
      stimulus: bi("To versjoner av en oppdiktet møtebeskjed:", "To versjonar av ein oppdikta møtebeskjed:"),
      passages: [
        { id: "update-old", text: bi("Første beskjed: Møtet begynner onsdag klokka 10.", "Første beskjed: Møtet byrjar onsdag klokka 10.") },
        { id: "update-new", text: bi("Oppdatert beskjed: Starten er flyttet til onsdag klokka 11.", "Oppdatert beskjed: Starten er flytta til onsdag klokka 11.") },
        { id: "update-place", text: bi("Vi bruker fortsatt rom 4.", "Vi bruker framleis rom 4.") },
      ],
      options: [
        { label: bi("Onsdag klokka 11", "Onsdag klokka 11"), verdict: "MATCHED", evidenceIds: ["update-new"], feedback: bi("Den oppdaterte beskjeden erstatter starttidspunktet i den første. Tekststedet støtter det nye tidspunktet.", "Den oppdaterte beskjeden erstattar starttidspunktet i den første. Tekststaden støttar det nye tidspunktet.") },
        { label: bi("Onsdag klokka 10", "Onsdag klokka 10"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Det var det første tidspunktet. Oppdateringen sier at starten er flyttet.", "Det var det første tidspunktet. Oppdateringa seier at starten er flytta.") },
        { label: bi("Klokka 4", "Klokka 4"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("4 er romnummeret, ikke møtets starttid.", "4 er romnummeret, ikkje starttida for møtet.") },
      ],
      hint: bi("Se etter oppdatert og flyttet. Hva er endret, og hva er fortsatt likt?", "Sjå etter oppdatert og flytta. Kva er endra, og kva er framleis likt?"),
      model: bi("Svar: Onsdag klokka 11. Tekstbevis: Den oppdaterte beskjeden flytter starten til klokka 11.", "Svar: Onsdag klokka 11. Tekstbevis: Den oppdaterte beskjeden flyttar starten til klokka 11."),
      explanation: bi("Begge klokkeslettene står i teksten, men bare det oppdaterte tidspunktet gjelder nå i denne beskjeden.", "Begge klokkesletta står i teksten, men berre det oppdaterte tidspunktet gjeld no i denne beskjeden."),
      reflection: bi("Hvilken opplysning ble ikke endret?", "Kva opplysning vart ikkje endra?"), evidenceRetry: retry,
    }),
    evidence({ id: "evidence-scope", prompt: bi("Kan vi si at alle i gruppen vil begynne med opplesning?", "Kan vi seie at alle i gruppa vil byrje med opplesing?"),
      stimulus: bi("En oppdiktet samtale før en leseoppgave:", "Ein oppdikta samtale før ei leseoppgåve:"),
      passages: [
        { id: "scope-ida", text: bi("Ida sier: «Jeg vil gjerne få teksten lest høyt.»", "Ida seier: «Eg vil gjerne få teksten lesen høgt.»") },
        { id: "scope-noor", text: bi("Noor sier: «Jeg vil lese stille først.»", "Noor seier: «Eg vil lese stille først.»") },
        { id: "scope-others", text: bi("De to andre har ikke sagt hva de ønsker.", "Dei to andre har ikkje sagt kva dei ønskjer.") },
      ],
      options: [
        { label: bi("Ja, fordi Ida ønsker det", "Ja, fordi Ida ønskjer det"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Idas ønske gjelder Ida. Det kan ikke gjøres til et ønske for hele gruppen.", "Ida sitt ønske gjeld Ida. Det kan ikkje gjerast til eit ønske for heile gruppa.") },
        { label: bi("Ingen ønsker opplesning", "Ingen ønskjer opplesing"), verdict: "TRY_AGAIN", evidenceIds: [], feedback: bi("Ida ber uttrykkelig om opplesning, så ingen blir for sterkt.", "Ida ber uttrykkeleg om opplesing, så ingen blir for sterkt.") },
        { label: bi("Nei, Noor ønsker å lese stille først", "Nei, Noor ønskjer å lese stille først"), verdict: "MATCHED", evidenceIds: ["scope-noor"], feedback: bi("Noors uttalte ønske er et moteksempel til påstanden om alle. Det forteller fortsatt ikke hva de to andre ønsker.", "Noor sitt uttalte ønske er eit motdøme til påstanden om alle. Det fortel framleis ikkje kva dei to andre ønskjer.") },
      ],
      hint: bi("En påstand om alle må passe med hver person som er beskrevet. Finn et konkret moteksempel.", "Ein påstand om alle må passe med kvar person som er skildra. Finn eit konkret motdøme."),
      model: bi("Svar: Nei. Tekstbevis: Noor ønsker å lese stille først. De to andre sine ønsker er uavklarte.", "Svar: Nei. Tekstbevis: Noor ønskjer å lese stille først. Ønska til dei to andre er uavklarte."),
      explanation: bi("Vi skiller mellom ett ønske, et moteksempel og manglende informasjon. Ett valg bestemmer ikke hva en hel gruppe ønsker.", "Vi skil mellom eitt ønske, eit motdøme og manglande informasjon. Eitt val avgjer ikkje kva ei heil gruppe ønskjer."),
      reflection: bi("Hvordan kunne gruppen få avklart støttevalgene uten å gjette?", "Korleis kunne gruppa få avklart støttevala utan å gjette?"), evidenceRetry: retry,
    }),
  ],
});
